import { PartnerPlatform, PartnerCategory } from "@/types/partner";

export const partnerCategories: { id: string; label: string; category?: PartnerCategory }[] = [
  { id: "all", label: "All Platforms" },
  { id: "marketing", label: "Digital Marketing", category: "Digital Marketing & Advertising" },
  { id: "cloud", label: "Cloud & Infrastructure", category: "Cloud & Infrastructure" },
  { id: "ecommerce", label: "E-commerce & Business", category: "E-commerce & Business Platforms" },
  { id: "payments", label: "Payments & Comms", category: "Payments & Communication" },
  { id: "development", label: "Development & Tech", category: "Development & Technology Ecosystem" },
];

export const partnerPlatforms: PartnerPlatform[] = [
  // 1. Digital Marketing & Advertising
  {
    id: "google",
    name: "Google",
    category: "Digital Marketing & Advertising",
    description: "Google Ads, Analytics, marketing and business growth.",
    website: "https://ads.google.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 1,
    altText: "Google technology ecosystem and marketing platforms",
    color: "#4285F4",
  },
  {
    id: "meta",
    name: "Meta",
    category: "Digital Marketing & Advertising",
    description: "Facebook and Instagram advertising, social media marketing and customer acquisition.",
    website: "https://www.meta.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 2,
    altText: "Meta advertising and social ecosystem",
    color: "#0668E1",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    category: "Digital Marketing & Advertising",
    description: "Microsoft Advertising and Microsoft business technology ecosystem.",
    website: "https://about.ads.microsoft.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 3,
    altText: "Microsoft advertising and business ecosystem",
    color: "#00A4EF",
  },

  // 2. Cloud & Infrastructure
  {
    id: "aws",
    name: "AWS",
    category: "Cloud & Infrastructure",
    description: "Cloud infrastructure, scalable applications and SaaS deployments.",
    website: "https://aws.amazon.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 4,
    altText: "AWS cloud platform and scalable infrastructure",
    color: "#FF9900",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "Cloud & Infrastructure",
    description: "DNS, CDN, security, performance and application protection.",
    website: "https://www.cloudflare.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 5,
    altText: "Cloudflare security, CDN and edge infrastructure",
    color: "#F38020",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Cloud & Infrastructure",
    description: "Modern web applications, Next.js deployments and scalable frontend infrastructure.",
    website: "https://vercel.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 6,
    altText: "Vercel frontend cloud and Next.js infrastructure",
    color: "#000000",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    category: "Cloud & Infrastructure",
    description: "Cloud infrastructure and application hosting for startups and growing businesses.",
    website: "https://www.digitalocean.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 7,
    altText: "DigitalOcean cloud infrastructure and hosting",
    color: "#0080FF",
  },
  {
    id: "hostinger",
    name: "Hostinger",
    category: "Cloud & Infrastructure",
    description: "Website hosting, domains and business website infrastructure.",
    website: "https://www.hostinger.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 8,
    altText: "Hostinger website hosting and infrastructure",
    color: "#673DE6",
  },

  // 3. E-commerce & Business Platforms
  {
    id: "shopify",
    name: "Shopify",
    category: "E-commerce & Business Platforms",
    description: "E-commerce websites, online stores and custom integrations.",
    website: "https://www.shopify.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 9,
    altText: "Shopify e-commerce platform and custom integrations",
    color: "#96BF48",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "E-commerce & Business Platforms",
    description: "CRM, marketing automation, sales and customer growth solutions.",
    website: "https://www.hubspot.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 10,
    altText: "HubSpot CRM and marketing automation platform",
    color: "#FF7A59",
  },
  {
    id: "atlassian",
    name: "Atlassian",
    category: "E-commerce & Business Platforms",
    description: "Jira, Confluence and software project management workflows.",
    website: "https://www.atlassian.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 11,
    altText: "Atlassian Jira and Confluence workflow platforms",
    color: "#0052CC",
  },

  // 4. Payments & Communication
  {
    id: "stripe",
    name: "Stripe",
    category: "Payments & Communication",
    description: "Payment integration, subscriptions, SaaS billing and e-commerce payments.",
    website: "https://stripe.com",
    status: "Platform Integration",
    officialPartner: false,
    displayOrder: 12,
    altText: "Stripe payments, billing, and subscription platform",
    color: "#635BFF",
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "Payments & Communication",
    description: "SMS, WhatsApp, voice, OTP and customer communication solutions.",
    website: "https://www.twilio.com",
    status: "Platform Integration",
    officialPartner: false,
    displayOrder: 13,
    altText: "Twilio SMS, voice, WhatsApp, and communication platform",
    color: "#F22F46",
  },

  // 5. Development & Technology Ecosystem
  {
    id: "github",
    name: "GitHub",
    category: "Development & Technology Ecosystem",
    description: "Source code management, collaboration, CI/CD and development workflows.",
    website: "https://github.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 14,
    altText: "GitHub version control, CI/CD, and developer ecosystem",
    color: "#24292F",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "Development & Technology Ecosystem",
    description: "Modern database solutions for scalable applications.",
    website: "https://www.mongodb.com",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 15,
    altText: "MongoDB modern NoSQL database solutions",
    color: "#00ED64",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "Development & Technology Ecosystem",
    description: "Reliable relational database technology for production applications and SaaS platforms.",
    website: "https://www.postgresql.org",
    status: "Technology Ecosystem",
    officialPartner: false,
    displayOrder: 16,
    altText: "PostgreSQL enterprise relational database technology",
    color: "#336791",
  },
];
